/* CNINFO Drive Gateway: institution research and market datasets */
const DEFAULT_BASE_PATH='CNINFO/机构调研'; const DEFAULT_DRAGON_TIGER_PATH='CNINFO/龙虎榜'; const DEFAULT_MAX_BYTES=35*1024*1024;
function initialize(){const p=PropertiesService.getScriptProperties();let token=p.getProperty('UPLOAD_TOKEN');if(!token){token=newToken_();p.setProperty('UPLOAD_TOKEN',token)}if(!p.getProperty('BASE_PATH'))p.setProperty('BASE_PATH',DEFAULT_BASE_PATH);if(!p.getProperty('DATASET_DRAGON_TIGER_PATH'))p.setProperty('DATASET_DRAGON_TIGER_PATH',DEFAULT_DRAGON_TIGER_PATH);if(!p.getProperty('MAX_BYTES'))p.setProperty('MAX_BYTES',String(DEFAULT_MAX_BYTES));const info=setupInfo_(true);console.log(JSON.stringify(info,null,2));return info}
function rotateUploadToken(){const token=newToken_();PropertiesService.getScriptProperties().setProperty('UPLOAD_TOKEN',token);const info=setupInfo_(true);console.log(JSON.stringify(info,null,2));return info}
function configureArchive(rootFolderId,basePath){const p=PropertiesService.getScriptProperties();if(rootFolderId){DriveApp.getFolderById(rootFolderId).getName();p.setProperty('ROOT_FOLDER_ID',String(rootFolderId).trim())}else p.deleteProperty('ROOT_FOLDER_ID');p.setProperty('BASE_PATH',String(basePath||DEFAULT_BASE_PATH).trim());return setupInfo_(false)}
function configureDataset(dataset,basePath){if(String(dataset)!=='dragon_tiger')throw new Error('当前仅支持数据集：dragon_tiger');PropertiesService.getScriptProperties().setProperty('DATASET_DRAGON_TIGER_PATH',String(basePath||DEFAULT_DRAGON_TIGER_PATH).trim());return setupInfo_(false)}
function doGet(){return jsonOutput_({ok:true,service:'CNINFO Drive Gateway',configured:Boolean(PropertiesService.getScriptProperties().getProperty('UPLOAD_TOKEN')),basePath:basePath_().join('/'),datasets:{dragon_tiger:datasetPath_('dragon_tiger').join('/')}})}
function doPost(event){try{const text=event&&event.postData?event.postData.contents:'';if(!text)return jsonOutput_({ok:false,code:'empty_request',error:'请求正文为空'});const payload=JSON.parse(text);verifyToken_(payload.token);if(payload.operation==='ping')return jsonOutput_({ok:true,result:{service:'CNINFO Drive Gateway',base_path:basePath_().join('/'),datasets:{dragon_tiger:datasetPath_('dragon_tiger').join('/')}}});const lock=LockService.getScriptLock();if(!lock.tryLock(30000))throw new Error('另一个上传任务正在运行，请稍后重试');try{let result;if(payload.operation==='upsert')result=upsertAnnouncement_(payload);else if(payload.operation==='run_file')result=upsertRunFile_(payload);else if(payload.operation==='dataset_file')result=upsertDatasetFile_(payload);else throw new Error('不支持的 operation: '+payload.operation);return jsonOutput_({ok:true,result:result})}finally{lock.releaseLock()}}catch(error){return jsonOutput_({ok:false,code:'request_failed',error:error&&error.message?error.message:String(error)})}}
function upsertAnnouncement_(p){requireFields_(p,['announcement_id','publish_date','sha256','file_name','mime_type','content_base64']);validateDate_(String(p.publish_date),'publish_date');const d=String(p.publish_date),segments=basePath_().concat([d.slice(0,4),d.slice(0,7),d]);return upsertFile_(segments,p,{cninfo_announcement_id:String(p.announcement_id),cninfo_sha256:String(p.sha256),cninfo_stock_code:String(p.stock_code||''),cninfo_publish_date:d,cninfo_format:String(p.format_detected||'')})}
function upsertRunFile_(p){requireFields_(p,['run_id','sha256','file_name','mime_type','content_base64']);const runId=String(p.run_id),year=/^\d{6}/.test(runId)?runId.slice(0,4):'unknown',ym=/^\d{6}/.test(runId)?runId.slice(0,4)+'-'+runId.slice(4,6):'unknown';return upsertFile_(basePath_().concat(['_runs',year,ym,runId]),p,{cninfo_announcement_id:'run:'+runId+':'+String(p.file_name),cninfo_sha256:String(p.sha256),cninfo_run_id:runId,cninfo_format:String(p.file_name).split('.').pop().toLowerCase()})}
function upsertDatasetFile_(p){requireFields_(p,['dataset','data_date','sha256','file_name','mime_type','content_base64']);const dataset=String(p.dataset),d=String(p.data_date);validateDate_(d,'data_date');return upsertFile_(datasetPath_(dataset).concat([d.slice(0,4),d.slice(0,7),d]),p,{cninfo_announcement_id:'dataset:'+dataset+':'+d+':'+String(p.file_name),cninfo_sha256:String(p.sha256),cninfo_dataset:dataset,cninfo_data_date:d,cninfo_format:String(p.file_name).split('.').pop().toLowerCase()})}
function upsertFile_(segments,p,metadata){const name=String(p.file_name||'');if(!name||/[\\/]/.test(name))throw new Error('file_name 不能为空且不能包含路径分隔符');const folder=ensurePath_(rootFolder_(),segments),existing=findByAnnouncementId_(folder,metadata.cninfo_announcement_id),old=existing?readMetadata_(existing):{},oldVersion=Number(old.cninfo_version||0),drivePath=segments.concat([name]).join('/');if(existing&&old.cninfo_sha256===metadata.cninfo_sha256)return{status:'skipped',file_id:existing.getId(),drive_path:drivePath,version:oldVersion||1,web_view_link:existing.getUrl()};const bytes=Utilities.base64Decode(String(p.content_base64)),max=Number(PropertiesService.getScriptProperties().getProperty('MAX_BYTES')||DEFAULT_MAX_BYTES);if(bytes.length>max)throw new Error('文件超过 Apps Script 上限');const version=oldVersion+1,blob=Utilities.newBlob(bytes,String(p.mime_type||'application/octet-stream'),name),created=folder.createFile(blob);metadata.cninfo_version=String(version);created.setDescription(JSON.stringify(metadata));if(existing)existing.setTrashed(true);return{status:existing?'updated':'created',file_id:created.getId(),drive_path:drivePath,version:version,web_view_link:created.getUrl()}}
function rootFolder_(){const id=PropertiesService.getScriptProperties().getProperty('ROOT_FOLDER_ID');return id?DriveApp.getFolderById(id):DriveApp.getRootFolder()}
function basePath_(){return splitPath_(PropertiesService.getScriptProperties().getProperty('BASE_PATH')||DEFAULT_BASE_PATH,'BASE_PATH')}
function datasetPath_(dataset){if(String(dataset)!=='dragon_tiger')throw new Error('不支持的数据集：'+dataset);return splitPath_(PropertiesService.getScriptProperties().getProperty('DATASET_DRAGON_TIGER_PATH')||DEFAULT_DRAGON_TIGER_PATH,'DATASET_DRAGON_TIGER_PATH')}
function splitPath_(v,label){const s=String(v).split('/').map(x=>x.trim()).filter(Boolean);if(!s.length)throw new Error(label+' 不能为空');return s}
function ensurePath_(root,segments){let p=root;segments.forEach(name=>{const found=p.getFoldersByName(String(name));p=found.hasNext()?found.next():p.createFolder(String(name))});return p}
function findByAnnouncementId_(folder,id){const files=folder.getFiles();while(files.hasNext()){const file=files.next(),m=readMetadata_(file);if(m.cninfo_announcement_id===String(id))return file}return null}
function readMetadata_(file){try{return JSON.parse(file.getDescription()||'{}')}catch(error){return{}}}
function verifyToken_(provided){const expected=PropertiesService.getScriptProperties().getProperty('UPLOAD_TOKEN');if(!expected)throw new Error('网关尚未初始化，请先运行 initialize()');if(!provided||String(provided)!==expected)throw new Error('上传令牌无效')}
function requireFields_(p,fields){fields.forEach(f=>{if(p[f]===undefined||p[f]===null||p[f]==='')throw new Error('缺少字段：'+f)})}
function validateDate_(v,f){if(!/^\d{4}-\d{2}-\d{2}$/.test(String(v)))throw new Error(f+' 必须是 YYYY-MM-DD')}
function newToken_(){return Utilities.getUuid().replace(/-/g,'')+Utilities.getUuid().replace(/-/g,'')}
function setupInfo_(includeToken){const p=PropertiesService.getScriptProperties(),r={basePath:basePath_().join('/'),datasets:{dragon_tiger:datasetPath_('dragon_tiger').join('/')},rootFolderId:p.getProperty('ROOT_FOLDER_ID')||'My Drive root',maxBytes:Number(p.getProperty('MAX_BYTES')||DEFAULT_MAX_BYTES)};if(includeToken)r.uploadToken=p.getProperty('UPLOAD_TOKEN');return r}
function jsonOutput_(payload){return ContentService.createTextOutput(JSON.stringify(payload)).setMimeType(ContentService.MimeType.JSON)}
